service: selfie2anime-image-handler

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

custom:
  pythonRequirements:
    dockerizePip: non-linux
    noDeploy: []
  customDomain:
    domainName: api.selfie2anime.com
    basePath: analysis
    stage: ${self:provider.stage}
    createRoute53Record: true

package:
  exclude:
    - .venv/**
    - node_modules/**

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

functions:
  selfie:
    handler: handler.selfie
    events:
      - http:
          path: selfie
          method: post